### ISSUE TITLE
Sin tener internet activado, si se entra en Noticias ó Calendario, al querer configurar los canales la app crashea

### ISSUE THREAD

**Issue by spaciuk** [tomasguti/utn-movil#32]

**Comment by jcramosfrsf** [comment]
Me pasa lo mismo con 'internet activado', incluso conectado a Wifi.
Creemos que tiene algo que ver con la versión de android o el celular. en mi caso, android 4.4.2

**Comment by tomasguti** [comment]
Arreglado, era un error de lógica que afectaba a todas las versiones la primera vez que corriamos la app.
