### ISSUE TITLE
Problemas al Seleccionar 'Canales'

### ISSUE THREAD

**Issue by jcramosfrsf** [tomasguti/utn-movil#38]
Tanto en Noticia, como en Calendario, cuando quiero seleccionar Canales, me aparece el mensaje: "Error buscando los canales desde el servidor".
Estoy utilizando una red wireless de la facultad (eduroam)

**Comment by tomasguti** [comment]
Aparece cuando la respuesta del servidor demora más de 6 segundos. Confirmo que está funcionando estable hace más de una semana. Es muy probable que sea un problema relacionado con la red. Habría que probar con otras para confirmar (con la frsfpublica andaba bien cuando fuimos el viernes).

![2016-08-02 18_33_35-tomasguti meanstack-1-vm_ _apps_utn-movil-backend](https://cloud.githubusercontent.com/assets/5039660/17346118/af087d6e-58df-11e6-8e44-ff062470ea95.png)
