### ISSUE TITLE
Backend: Alta de Eventos

### ISSUE THREAD

**Issue by jcramosfrsf** [tomasguti/utn-movil#47]
Definí un evento para el día 18/08/2016, indicando que 'Emita Notificación'. En el celular me llega la notificación, pero no aparece en el Calendario. ¿No debería aparecer?
El evento es para  el Dpto Sistemas que tengo configurado como canal activo.

**Comment by tomasguti** [comment]
Issue movido al proyecto de backend
https://github.com/tomasguti/utn-movil-backend/issues
