### ISSUE TITLE
Backend: General

### ISSUE THREAD

**Issue by jcramosfrsf** [tomasguti/utn-movil#48]
Tanto para noticias como para eventos debería existir un 'historial' que me permita ver cuáles son los registros existentes, eventualmente modificarlos y hasta borrarlos.
¿No deberíamos tener una 'vigencia' tanto de una noticia como un evento?. Es decir, hasta cuándo es visible o válida una noticia u evento.
La vigencia sería un 'fecha desde - Fecha hasta' (cuando pasa el hasta, ya no se muestra).

**Comment by tomasguti** [comment]
Issue movido al proyecto de backend
[https://github.com/tomasguti/utn-movil-backend/issues](url)
